# Generated by Django 6.0.4 on 2026-04-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('requests_app', '0003_requestauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='requests_app.request')),
            ],
        ),
    ]
