# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_requestmaterialitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
    ]
