# Generated by Django 6.0.4 on 2026-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_remove_request_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='requires_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='requires_materials',
            field=models.BooleanField(default=False),
        ),
    ]
