# Generated by Django 6.0.4 on 2026-06-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0007_request_stock_deducted_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='stock_returned',
            field=models.BooleanField(default=False, help_text='Indicates whether stock has been returned for this request.'),
        ),
        migrations.AddField(
            model_name='request',
            name='stock_returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
