# Generated by Django 6.0.4 on 2026-06-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0008_request_stock_returned_request_stock_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='return_reason',
            field=models.TextField(blank=True, help_text='Reason why material was returned to stock.'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OUT', 'Stock Out'), ('IN', 'Stock In'), ('RETURN', 'Return to Stock')], max_length=10),
        ),
    ]
