# Generated by Codex on 2026-06-10

from django.db import migrations, models


def mark_existing_permission_request_types(apps, schema_editor):
    RequestType = apps.get_model("requests_app", "RequestType")

    for request_type in RequestType.objects.all():
        name = (request_type.name or "").lower()
        code = (request_type.code or "").lower()

        if "permission" in name or "permission" in code or "general" in name or "general" in code:
            request_type.is_permission_request = True
            request_type.save(update_fields=["is_permission_request"])


def unmark_existing_permission_request_types(apps, schema_editor):
    RequestType = apps.get_model("requests_app", "RequestType")
    RequestType.objects.update(is_permission_request=False)


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0009_stockmovement_return_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttype",
            name="is_permission_request",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_permission_request_types,
            unmark_existing_permission_request_types,
        ),
    ]
