# Generated by Django 6.0.4 on 2026-06-10 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0010_requesttype_is_permission_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestapproval',
            name='acted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_request_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestapproval',
            name='alternate_approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alternate_request_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
