# Generated by Django 6.0.4 on 2026-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0011_requestapproval_acted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='material_issue_note',
            field=models.TextField(blank=True),
        ),
    ]
