# Generated by Django 6.0.4 on 2026-05-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_stock',
            field=models.BooleanField(default=False, verbose_name='Can Manage Stock Reports'),
        ),
    ]
