# Generated by Django 6.0.4 on 2026-10-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_can_manage_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_administration_reports',
            field=models.BooleanField(default=False, verbose_name='Can view administration reports'),
        ),
    ]
